version: "3.5"

services:
  debian-10-core:
    image: uim/uim-debian-10-core
    build:
      context: ci/dockerfiles
      dockerfile: debian-10-core.dockerfile
    volumes:
      - .:/source:delegated
  debian-10-gtk2:
    image: uim/uim-debian-10-gtk2
    build:
      context: ci/dockerfiles
      dockerfile: debian-10-gtk2.dockerfile
    volumes:
      - .:/source:delegated
  debian-10-gtk3:
    image: uim/uim-debian-10-gtk3
    build:
      context: ci/dockerfiles
      dockerfile: debian-10-gtk3.dockerfile
    volumes:
      - .:/source:delegated
  debian-10-qt4:
    image: uim/uim-debian-10-qt4
    build:
      context: ci/dockerfiles
      dockerfile: debian-10-qt4.dockerfile
    volumes:
      - .:/source:delegated
  debian-10-qt5:
    image: uim/uim-debian-10-qt5
    build:
      context: ci/dockerfiles
      dockerfile: debian-10-qt5.dockerfile
    volumes:
      - .:/source:delegated
  debian-10-release:
    image: uim/uim-debian-10-release
    build:
      context: ci/dockerfiles
      dockerfile: debian-10-release.dockerfile
    volumes:
      - .:/source:delegated
