name: Linux
on:
  - push
  - pull_request
jobs:
  core:
    name: Core
    strategy:
      fail-fast: false
      matrix:
        image:
          - debian-10
        type:
          - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install dependencies to generate configure
        run: |
          sudo apt update
          sudo apt install -y -V \
            autoconf \
            autopoint \
            intltool \
            libtool \
            pkg-config
      - name: Generate configure
        run: |
          ./autogen.sh
          cd sigscheme
          ./autogen.sh
      - name: Build Docker image
        run: |
          docker-compose build ${{ matrix.image }}
      - name: Run Docker image
        run: |
          docker-compose run ${{ matrix.image }} \
            /source/ci/${{ matrix.type }}.sh
