name: Linux
on:
  - push
  - pull_request
jobs:
  core:
    name: Core
    strategy:
      fail-fast: false
      matrix:
        image:
          - debian-10
        type:
          - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install packages
        run: |
          sudo apt update
          sudo apt install -y -V \
            autoconf-archive \
            automake1.11 \
            autotools-dev \
            intltool
      - name: Generate configure
        run: |
          ./autogen.sh
      - name: Build Docker image
        run: |
          docker-compose build ${{ matrix.image }}
      - name: Run Docker image
        run: |
          docker-compose run ${{ matrix.image }} \
            /source/ci/${{ matrix.type }}.sh
